[package]
name = "tokio-memcache"
version = "0.1.0"
authors = ["Matt Williams <matwilliams@hotmail.com>"]
license = "MIT"

[dependencies]
futures = "0.1.7"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
nom = "^2.0"
